### ISSUE TITLE
Xcode 6.3.1 issue

### ISSUE THREAD

**Issue by dkao1222** [TDAbboud/WeightLogger#1]
under Xcode 6.3.1 
I write the follow youtube guide:
@IBAction func betSavePressed(sender: AnyObject) {
        //Save Data
        var appDel: AppDelegate = (UIApplication.sharedApplication().delegate as! AppDelegate)
        var context: NSManagedObjectContext = appDel.managedObjectContext!
        let ent = NSEntityDescription.entityForName("UserWeights", inManagedObjectContext: context)!\
        var newWeight = UserWeights()

but I can't get var newWeight = UserWeights(entity: ent, insertIntoManagedObjectContext: context)
how I can fix this issue

```
}
```

**Comment by tabboud** [comment]
Did you import CoreData into the file? Double check your data model to make sure you inherited from NSManagedObject and make sure your entity is correct.

**Comment by dkao1222** [comment]
Dear Tony :

I has make sure my code , has import CoreData, but always not show entity,
Please help me check this

2015-05-02 22:30 GMT+08:00 Tony Abboud notifications@github.com:

> Did you import CoreData into the file? Double check your data model to
> make sure you inherited from NSManagedObject and make sure your entity is
> correct.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TDAbboud/WeightLogger/issues/1#issuecomment-98365282.

## 

Best Regards
Dragon Kao
email:dkao1222@gmail.com

**Comment by tabboud** [comment]
Can you send me the project. I can take a look at it and fix the problem

**Comment by dkao1222** [comment]
Dear Tony :

Thank's your reply , please refer attach file , thank you.

2015-05-03 0:41 GMT+08:00 Tony Abboud notifications@github.com:

> Can you send me the project. I can take a look at it and fix the problem
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TDAbboud/WeightLogger/issues/1#issuecomment-98377234.

## 

Best Regards
Dragon Kao
email:dkao1222@gmail.com

**Comment by tabboud** [comment]
This seems like a bug with Xcode. If you create another variable after the one you have (newWeight), and try to instantiate the UserWeights class, you get the other init method. So what you can do is just write the init method explicitly and it will work fine. Again this seems to be a bug with Xcode and not your code.

**Comment by dkao1222** [comment]
Dear Tony :

If this bug is Xcode issue , how can fix or how to write to right

從我的 iPad 傳送
